---
# default site settings
# configure these values for your project
project:
  name: "vxlang"
  owner: "vxlang"
  repo: "https://vxlang.github.io/"
  version: "0.8.9"

collections:
  guides:
    output: true
    permalink: "/:collection/:path/"
    title: Guides
    tab-order: 1
  update:
    output: true
    permalink: "/:collection/:path/"
    title: Version History
    tab-order: 2

highlighter: rouge
permalink: pretty
sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-remote-theme
remote_theme: pixeldroid/programming-pages
